# List of data Journals
List of journals that publish datapapers

-	Acta Crystallographica E: Structure Reports Online
-	[Atomic Data and Nuclear Data Tables](http://www.journals.elsevier.com/atomic-data-and-nuclear-data-tables/) (Elsevier)
- [Biodiversity Data Journal](http://biodiversitydatajournal.com/) (Pensoft Publishers)
- [Biomedical Data Journal](http://biomed-data.eu/) (Procon Ltd.)
- BioRisk
-	BMC Bioinformatics
-	BMC Biology
-	BMC Biophysics
-	BMC Biotechnology
-	BMC Cancer
-	BMC Cell Biology
-	BMC Complementary & Alternative Medicine
-	BMC Dermatology
-	BMC Developmental Biology
-	BMC Ecology
-	BMC Evolutionary Biology
-	BMC Gastroenterology
-	BMC Genetics
-	BMC Genomics
-	BMC Geriatrics
-	BMC Immunology
-	BMC Infectious Diseases
-	BMC Medical Education
-	BMC Medical Genetics
-	BMC Medical Genomics
-	BMC Medical Imaging
-	BMC Medical Informatics & Decision Making
-	BMC Medical Research Methodology
-	BMC Microbiology
-	BMC Molecular Biology
-	BMC Musculoskeletal Disorders
-	BMC Nephrology
-	BMC Neuroscience
-	BMC Ophthalmology
-	BMC Palliative Care
-	BMC Pharmacology & Toxicology
-	BMC Plant Biology
-	BMC Pregnancy & Childbirth
-	BMC Psychiatry
-	BMC Public Health
-	BMC Pulmonary Medicine
-	[BMC Research Notes](http://bmcresnotes.biomedcentral.com/) (Biomed Central)
-	BMC Structural Biology
-	BMC Systems Biology
-	BMC Urology
-	[Brain and Behavior](https://onlinelibrary.wiley.com/page/journal/21579032/homepage/data_set.htm)
-	[Chemical Data Collections](http://www.journals.elsevier.com/chemical-data-collections) (Elsevier)
-	[Data](http://www.mdpi.com/journal/data/about) (MDPI)
-	[Data in Brief](http://www.journals.elsevier.com/data-in-brief) (Elsevier)
-	[Dataset Papers in Science](http://www.hindawi.com/journals/dpis/) (Hindawi Publishing Corporation)
-	[Earth System Science Data](http://www.earth-system-science-data.net/) - ESSD (Copernicus Publications)
-	[Ecological Archives](http://esapubs.org/archive/instruct_d.htm) (Ecological Society of America - ESA)
-	Ecological Research
-	Ecology
-	[European Data Watch](http://www.ratswd.de/publikationen/european-data-watch)
-	[F1000Research](http://f1000research.com/)
-	[Genomics Data](http://www.journals.elsevier.com/genomics-data) (Elsevier)
-	Geochemistry, Geophysics, Geosystems
-	[Geoscience Data Journal](http://onlinelibrary.wiley.com/journal/10.1002/%28ISSN%292049-6060) (Wiley)
-	Geoscientific Model Development
-	[GigaScience](http://www.gigasciencejournal.com/) (Oxford University Press)
-	[International Journal of Robotics Research](http://ijr.sagepub.com/)
-	[Internet Archaeology](http://intarch.ac.uk/authors/data-papers.html)
-	Journal of Astronomical Data
-	[Journal of Chemical & Engineering Data](http://pubs.acs.org/journal/jceaax) (ACS Publications)
-	[Journal of Open Archeology Data](http://openarchaeologydata.metajnl.com/)
-	[Journal of Open Psychology Data](http://openpsychologydata.metajnl.com/) (JOPD) (Ubiquity Press)
-	Journal of Open Research Software
-	[Journal of Physical and Chemical Reference Data](http://scitation.aip.org/content/aip/journal/jpcrd/browse) (AIP Publishing)
-	Journal of Statistical Software
-	(Matters)[https://www.sciencematters.io/]
-	MycoKeys
-	Nature Conservation
-	NeoBiota
-	Neuroinformatics
-	[Nuclear Data Sheets](http://www.journals.elsevier.com/nuclear-data-sheets/) (Elsevier)
-	[Open Archaeology Data](http://openarchaeologydata.metajnl.com/) (Ubiquity Press)
-	[Open Data Journal for Agricultural Research](http://library.wur.nl/ojs/index.php/odjar/) (diverse)
-	[Open Health Data](http://openhealthdata.metajnl.com/) (Ubiquity Press)
-	[Open Journal of Bioresources](http://openbioresources.metajnl.com/) (Ubiquity Press)
-	[Open Network Biology](http://www.opennetworkbiology.com/) (BioMed Central)
-	PhytoKeys
-	PLoS ONE
-	[Research Data Journal for the Humanities and Social Sciences](http://dansdatajournal.nl/) (Brill)
-	[Scientific Data](http://www.nature.com/scientificdata/) (Nature Publishing Group)
-	SpringerPlus
-	Standards in Genomic Sciences
-	The [CODATA Data Science Journal](http://datascience.codata.org/)
-	ZooKeys


### Other links

https://mlibrarydata.wordpress.com/2014/05/09/data-journals/
https://www.forschungsdaten.org/index.php/Data_Journals
